global:
  resolve_timeout: 10m

route:
  group_by: ["alertname"]
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 10m
  receiver: "sns"

receivers:
  - name: "sns"
    sns_configs:
      - topic_arn: "${TOPIC_ARN}"
        send_resolved: true
        subject: "Cluster Alert" # safe and valid for AWS SNS parameter, whereas the default value (template) does not seem to be.
        sigv4:
          region: ap-northeast-1
          role_arn: "${ROLE_ARN}"

inhibit_rules: []

templates: []
